services:
  - type: web
    name: smollm-api
    runtime: node

    buildCommand: |
      npm install
      mkdir -p models
      curl -L \
      "https://huggingface.co/jc-builds/SmolLM2-135M-Instruct-Q4_K_M-GGUF/resolve/main/SmolLM2-135M-Instruct.Q4_K_M.gguf" \
      -o models/model.gguf

    startCommand: npm start
